exclude: |
  (?x)(
    ^openstudio_model/|
    ^docs/conf.py|
    ^fmus/jmodelica.py|
    ^fmus/parser.py
  )

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
        args: [ '--in-place', '--aggressive', '--aggressive', '--recursive', '--max-line-length=100', '--ignore=E501,E402,W503,W504,E731' ]
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: [ '--in-place', '--recursive', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports' ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [ '--ignore=E501,E402,W503,W504,E731,F401' ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
#        args: ['-m 3']  # vertical hanging
  - repo: local
    hooks:
      - id: modelica-fmt
        name: Modelica Formatter
        types: [file]
        files: \.(mo)$
        entry: modelicafmt
        args: ["-w"]
        language: system
